spring.application.name=TUYUBAHE-Ashrafu
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/hotelmngs
spring.datasource.username=postgres
 spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
 spring.mail.port=587    
spring.mail.username=ashraftuyubahe001@gmail.com 
spring.mail.password=uxvn mvjw tcbw wdgi

server.port=8081
